#!/bin/sh
set +x -e

: ${1?Target server must be set}

screen -p 0 -S mc-$1 -X eval 'stuff "say SERVER BACKUP STARTING IN 60 SECONDS."\\015'
sleep 45
screen -p 0 -S mc-$1 -X eval 'stuff "say SERVER BACKUP STARTING IN 15 SECONDS."\\015'
sleep 15
screen -p 0 -S mc-$1 -X eval 'stuff "say SERVER BACKUP STARTING. Server going read-only..."\\015'
screen -p 0 -S mc-$1 -X eval 'stuff "save-off"\\015'
screen -p 0 -S mc-$1 -X eval 'stuff "save-all"\\015'
sync
sleep 5 # Async wait to stop

# --- Archive target server backup
tar -C /opt/minecraft -czvf /opt/minecraft/backups/$1.tgz $1

# --- Export
/opt/scripts/export $1

screen -p 0 -S mc-$1 -X eval 'stuff "say SERVER BACKUP COMPLETE. Server going read-write."\\015'
screen -p 0 -S mc-$1 -X eval 'stuff "save-on"\\015'
